"""Add priority field to tasks

Revision ID: a50c4f6c734d
Revises: 3281b5f4d783
Create Date: 2026-02-23 08:13:42.112453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50c4f6c734d'
down_revision: Union[str, Sequence[str], None] = '3281b5f4d783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False, server_default='MEDIUM'))
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
